version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 881490102041.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose build
      - docker tag frontend-ui:latest 881490102041.dkr.ecr.ap-south-1.amazonaws.com/threatmap-frontend-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 881490102041.dkr.ecr.ap-south-1.amazonaws.com/threatmap-frontend-repo:latest
      - printf '[{"name":"ThreatmapFrontendContainer","imageUri":"%s"}]' 881490102041.dkr.ecr.ap-south-1.amazonaws.com/881490102041.dkr.ecr.ap-south-1.amazonaws.com/threatmap-frontend-repo:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json